#!/bin/bash
#

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u] project [project2 ...]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default /usr)"
    printf "\n\t-u displays this usage message and exits\n"
    printf "\nNo arguments: build aewan, configure with prefix=/usr, build\n"
    printf "\n'project' can be 'aewan'\n"
    exit 1
}

INSTALL=
PREFIX=/usr
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ -f aewan ] || {
  prefix="--prefix=/usr"
  [ "${PREFIX}" ] && prefix="--prefix=${PREFIX}"
  autoreconf -vi
  ./configure ${prefix}
  make
}
chmod +x aewan aecat aemakeflic

[ "${INSTALL}" ] && {
  [ -d ${PREFIX}/usr ] || sudo mkdir -p ${PREFIX}/usr
  [ -d ${PREFIX}/usr/bin ] || sudo mkdir -p ${PREFIX}/usr/bin
  sudo cp aewan aecat aemakeflic ${PREFIX}/usr/bin
  [ -d ${PREFIX}/usr/share ] || sudo mkdir -p ${PREFIX}/usr/share
  [ -d ${PREFIX}/usr/share/man ] || sudo mkdir -p ${PREFIX}/usr/share/man
  [ -d ${PREFIX}/usr/share/man/man1 ] || sudo mkdir -p ${PREFIX}/usr/share/man/man1
  [ -d ${PREFIX}/usr/share/man/man5 ] || sudo mkdir -p ${PREFIX}/usr/share/man/man5
  sudo cp man/man1/*.1 ${PREFIX}/usr/share/man/man1
  sudo cp man/man5/*.5 ${PREFIX}/usr/share/man/man5
}
